In [1]:
import pandas as pd
import numpy as np
from numpy import nan as na

In [2]:
df = pd.read_csv("data for panda exercise.csv")
df

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [3]:
df.shape

(48, 14)

In [4]:
df.columns

Index(['Student Code', 'Degree', 'Student Name', 'Mid', 'Quiz 1', 'Quiz 2',
       'Best of Quizzes', 'Assignment 1', 'Assignment 2',
       'Best of Assignments', 'Total Sessional (50)', 'Final (50)',
       'Total (100)', 'Grade'],
      dtype='object')

In [5]:
df.head(10)

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A

In [6]:
df.tail(10)

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [16]:
sum(df.Grade == 'A')

8

In [21]:
df[df['Best of Assignments']>5]

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [23]:
df[df.Mid >25].count()

Student Code            20
Degree                  20
Student Name            20
Mid                     20
Quiz 1                  20
Quiz 2                  18
Best of Quizzes         20
Assignment 1            20
Assignment 2            14
Best of Assignments     20
Total Sessional (50)    20
Final (50)              20
Total (100)             20
Grade                   20
dtype: int64

In [27]:
df [4:5]

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B

In [31]:
df

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Muhammad Ghazali Farid,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Muhammad Ghazali Farid,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Muhammad Ghazali Farid,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Muhammad Ghazali Farid,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Muhammad Ghazali Farid,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Muhammad Ghazali Farid,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Muhammad Ghazali Farid,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Muhammad Ghazali Farid,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Muhammad Ghazali Farid,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Muhammad Ghazali Farid,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Muhammad Ghazali Farid,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
11,022-14-110591,BS(CS),Muhammad Ghazali Farid,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B
12,022-15-110994,BS(CS),Muhammad Ghazali Farid,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Muhammad Ghazali Farid,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Muhammad Ghazali Farid,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Muhammad Ghazali Farid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
16,022-14-110596,BS(CS),Muhammad Ghazali Farid,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Muhammad Ghazali Farid,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Muhammad Ghazali Farid,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Muhammad Ghazali Farid,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Ghazali Farid,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Ghazali Farid,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Ghazali Farid,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ghazali Farid,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Ghazali Farid,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Ghazali Farid,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Farid,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Ghazali Farid,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Ghazali Farid,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Ghazali Farid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Ghazali Farid,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Ghazali Farid,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Ghazali Farid,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Ghazali Farid,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Muhammad Ghazali Farid,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Muhammad Ghazali Farid,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Muhammad Ghazali Farid,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Muhammad Ghazali Farid,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
38,022-14-110229,BS(CS),Muhammad Ghazali Farid,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Muhammad Ghazali Farid,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Muhammad Ghazali Farid,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Muhammad Ghazali Farid,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Muhammad Ghazali Farid,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Muhammad Ghazali Farid,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Muhammad Ghazali Farid,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Muhammad Ghazali Farid,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Muhammad Ghazali Farid,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Muhammad Ghazali Farid,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [33]:
df[df['Student Name']=='Muhammad Ghazali Faridi']

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C

In [35]:
df.iloc[5:18,9:10]

    Best of Assignments
5                    10
6                    10
7                    10
8                     9
9                     8
10                    8
11                    5
12                   10
13                   10
14                    8
15                    0
16                    9
17                   11

In [38]:
df.iloc[1::2]

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [44]:
a = df.dropna()
a

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [49]:
df[(df['Grade'] == 'A') & df['Student Name'].str.startswith('A')]

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A

In [50]:
df[['Student Name', 'Assignment 1','Grade']][(df.Grade == 'A')]

           Student Name  Assignment 1 Grade
7      Aneebullah Niazi           8.0     A
9               Arsalan           8.0     A
10  Fatima Haider Warsi           8.0     A
19      Mohammad Hunain           8.0     A
25       Muhammad Faraz           8.0     A
34     Nazeer Bin Zafar           8.0     A
40          Sharif Taqi           8.0     A
45    Syeda Sabika Raza           9.0     A

In [60]:
df[df['Student Name'].str.contains('Ali')]

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C

In [3]:
df

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [4]:
df.fillna({'Quiz 1':5,'Quiz 2' :5, 'Assignment 1': -5, 'Assignment 2': -5,
           'Mid':df['Final (50)']*3/4,
           'Final (50)':df['Mid']*3/4}, inplace = True)

In [5]:
df

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,5.0,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,-5.0,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,-5.0,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,-5.0,8,46,45.0,91,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,-5.0,5,41,35.0,76,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,5.0,5.0,0,-5.0,-5.0,0,18,13.5,18,F
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,-5.0,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,5.0,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,5.0,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,-5.0,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,-5.0,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,-5.0,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,5.0,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,-5.0,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,-5.0,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,-5.0,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,-5.0,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,-5.0,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [9]:
 df['Status'] = df['Grade'].apply(lambda x : 'Fail' if x == 'F' else 'Pass')

In [10]:
df

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade,Status
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B,Pass
1,022-14-110233,BS(CS),Adeel Ahmed,17,5.0,5.0,5,8.0,10.0,10,32,18.0,50,F,Fail
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C,Pass
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,-5.0,2.0,2,23,23.0,46,F,Fail
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B,Pass
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B,Pass
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B,Pass
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A,Pass
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C,Pass
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,-5.0,8,44,40.0,84,A,Pass
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,-5.0,8,46,45.0,91,A,Pass
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,-5.0,5,41,35.0,76,B,Pass
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B,Pass
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C,Pass
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C,Pass
15,022-14-19916,BS(CS),Haseeb Sajid,18,5.0,5.0,0,-5.0,-5.0,0,18,13.5,18,F,Fail
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B,Pass
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B,Pass
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C,Pass
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A,Pass
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B,Pass
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C,Pass
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,-5.0,7,34,23.0,57,F,Fail
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,5.0,5,8.0,10.0,10,41,21.0,62,C,Pass
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B,Pass
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A,Pass
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,5.0,6,6.0,8.0,8,41,24.0,65,C,Pass
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B,Pass
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F,Fail
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,-5.0,6,30,9.0,39,F,Fail
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,-5.0,9,40,32.0,72,B,Pass
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,-5.0,10,44,29.0,73,B,Pass
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,5.0,2.0,2,8.0,10.0,10,21,8.0,29,F,Fail
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F,Fail
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A,Pass
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,-5.0,10.0,10,38,28.0,66,C,Pass
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,-5.0,9,43,27.0,70,B,Pass
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,-5.0,9,45,30.0,75,B,Pass
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F,Fail
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C,Pass
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A,Pass
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F,Fail
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C,Pass
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B,Pass
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,-5.0,9,41,22.0,63,C,Pass
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,-5.0,9,45,35.0,80,A,Pass
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C,Pass
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F,Fail

In [13]:
df['Total (100)'].rename('Grand Total',inplace = True)

0     70
1     50
2     63
3     46
4     77
5     71
6     74
7     85
8     61
9     84
10    91
11    76
12    73
13    67
14    65
15    18
16    72
17    70
18    60
19    91
20    71
21    60
22    57
23    62
24    77
25    86
26    65
27    71
28    57
29    39
30    72
31    73
32    29
33    51
34    86
35    66
36    70
37    75
38    39
39    68
40    81
41    57
42    67
43    79
44    63
45    80
46    65
47    46
Name: Grand Total, dtype: int64

In [15]:
df

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade,Status
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B,Pass
1,022-14-110233,BS(CS),Adeel Ahmed,17,5.0,5.0,5,8.0,10.0,10,32,18.0,50,F,Fail
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C,Pass
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,-5.0,2.0,2,23,23.0,46,F,Fail
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B,Pass
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B,Pass
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B,Pass
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A,Pass
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C,Pass
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,-5.0,8,44,40.0,84,A,Pass
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,-5.0,8,46,45.0,91,A,Pass
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,-5.0,5,41,35.0,76,B,Pass
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B,Pass
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C,Pass
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C,Pass
15,022-14-19916,BS(CS),Haseeb Sajid,18,5.0,5.0,0,-5.0,-5.0,0,18,13.5,18,F,Fail
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B,Pass
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B,Pass
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C,Pass
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A,Pass
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B,Pass
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C,Pass
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,-5.0,7,34,23.0,57,F,Fail
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,5.0,5,8.0,10.0,10,41,21.0,62,C,Pass
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B,Pass
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A,Pass
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,5.0,6,6.0,8.0,8,41,24.0,65,C,Pass
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B,Pass
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F,Fail
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,-5.0,6,30,9.0,39,F,Fail
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,-5.0,9,40,32.0,72,B,Pass
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,-5.0,10,44,29.0,73,B,Pass
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,5.0,2.0,2,8.0,10.0,10,21,8.0,29,F,Fail
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F,Fail
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A,Pass
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,-5.0,10.0,10,38,28.0,66,C,Pass
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,-5.0,9,43,27.0,70,B,Pass
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,-5.0,9,45,30.0,75,B,Pass
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F,Fail
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C,Pass
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A,Pass
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F,Fail
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C,Pass
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B,Pass
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,-5.0,9,41,22.0,63,C,Pass
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,-5.0,9,45,35.0,80,A,Pass
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C,Pass
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F,Fail

In [16]:
df.rename(columns = {'Total(100)':'Grand Total'}, inplace = True)

In [17]:
df['Sum of Quizzes'] = df['Quiz 1'] + df['Quiz 2']

In [19]:
df

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade,Status,Sum of Quizzes
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B,Pass,11.0
1,022-14-110233,BS(CS),Adeel Ahmed,17,5.0,5.0,5,8.0,10.0,10,32,18.0,50,F,Fail,10.0
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C,Pass,7.0
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,-5.0,2.0,2,23,23.0,46,F,Fail,9.0
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B,Pass,13.0
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B,Pass,15.0
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B,Pass,11.0
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A,Pass,15.0
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C,Pass,13.0
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,-5.0,8,44,40.0,84,A,Pass,14.0
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,-5.0,8,46,45.0,91,A,Pass,15.0
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,-5.0,5,41,35.0,76,B,Pass,13.0
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B,Pass,12.0
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C,Pass,12.0
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C,Pass,11.0
15,022-14-19916,BS(CS),Haseeb Sajid,18,5.0,5.0,0,-5.0,-5.0,0,18,13.5,18,F,Fail,10.0
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B,Pass,10.0
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B,Pass,13.0
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C,Pass,7.0
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A,Pass,15.0
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B,Pass,13.0
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C,Pass,15.0
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,-5.0,7,34,23.0,57,F,Fail,13.0
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,5.0,5,8.0,10.0,10,41,21.0,62,C,Pass,10.0
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B,Pass,9.0
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A,Pass,15.0
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,5.0,6,6.0,8.0,8,41,24.0,65,C,Pass,11.0
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B,Pass,14.0
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F,Fail,12.0
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,-5.0,6,30,9.0,39,F,Fail,8.0
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,-5.0,9,40,32.0,72,B,Pass,14.0
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,-5.0,10,44,29.0,73,B,Pass,12.0
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,5.0,2.0,2,8.0,10.0,10,21,8.0,29,F,Fail,7.0
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F,Fail,6.0
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A,Pass,15.0
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,-5.0,10.0,10,38,28.0,66,C,Pass,13.0
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,-5.0,9,43,27.0,70,B,Pass,14.0
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,-5.0,9,45,30.0,75,B,Pass,14.0
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F,Fail,12.0
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C,Pass,8.0
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A,Pass,15.0
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F,Fail,13.0
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C,Pass,11.0
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B,Pass,13.0
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,-5.0,9,41,22.0,63,C,Pass,12.0
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,-5.0,9,45,35.0,80,A,Pass,15.0
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C,Pass,13.0
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F,Fail,14.0